### ISSUE TITLE
update aws-sdk-sqs

### ISSUE THREAD

**Issue by CodySwannGT** [active-elastic-job/active-elastic-job#123]
Can this not be pinned at version 1 of this gem?

**Comment by joeyparis** [comment]
I'm not sure I understand the question. Do you want aws-sdk-sqs on version 1 or do you not?

**Comment by januszm** [comment]
@CodySwannGT looks like v1 is your only choice anyway: https://rubygems.org/gems/aws-sdk-sqs/versions
when aws-sdk-sqs 2+ is released, we can make a well-tested active-elastic-job release 2 compatible with the new sdk. But we can cross that bridge when we come to it

**Comment by CodySwannGT** [comment]
Thanks for the replies. You're absolutely right. This was complete user error. I apologize!
