### ISSUE TITLE
Question regarding active_storage_analysis

### ISSUE THREAD

**Issue by CarlChaappletree** [active-elastic-job/active-elastic-job#142]
Hi,

Anyone who can teach me what the active_storage_analysis and do? I have them in SQS queues.

- What does active_storage_analysis do?

- Is it ok the active_storage_analysis enqueued in the SQS without invoking?

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/45193415/155877609-c65b5fce-d331-4f42-89ca-2ce284cfaa46.png">

Thank you for reading!

**Comment by joeyparis** [comment]
I don't believe active_storage_analysis has anything to do with this gem. Unfortunately, I'm going to have to close this issue. I'm also not familiar enough with ActiveStorage to be of any help. Perhaps [this article](https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues) can help send you in the right direction.
