### ISSUE TITLE
/var/proxy/staging/nginx/conf.d/read_timeout.conf disappears

### ISSUE THREAD

**Issue by keisukekomeda** [active-elastic-job/active-elastic-job#143]
`/var/proxy/staging/nginx/conf.d/read_timeout.conf` disappears when elastic beanstalk configuration settings are updated.
And it causes that the long (longer than 1 minutes) jobs fail. (the job is treated as `fail`, and job becomes visible on SQS again.)

In this case, `predeploy` script seems not to be called.
However, I have no idea which hook might be the workaround for this problem.
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html#platforms-linux-extend.hooks.configdeploy

==================
Environment:
Elastic Beanstalk Platform: Ruby 2.7 running on 64bit Amazon Linux 2/3.4.4

Reproduction:
- use the same file `.platform/hooks/predeploy/nginx_read_timeout.sh` as in README.
- update some of Elastic Beanstalk configuration.
  - In my case, I enabled log file rotation to Amazon S3. -> After the environment update finished, `read_timout.conf` disappears.

**Comment by januszm** [comment]
It looks like we need this conf file in both hooks and confighooks 

`.platform/hooks/predeploy/...`
`.platform/confighooks/predeploy/...`

**Comment by keisukekomeda** [comment]
@joeyparis 
I created a PR to fix it #144 . (Only a small fix on README)

**Comment by joeyparis** [comment]
@keisukekomeda thank you for your contribution!
